/*

MIT License

Copyright (c) 2018 Federico Terzi

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <sstream>
#include "ParserException.h"

using namespace ninx::lexer::token;

ninx::parser::exception::ParserException::ParserException(int line, std::string &origin, const std::string &message)
        : runtime_error(
        make_message(line, origin, message)), line{line}, origin(origin) {

}

std::string
ninx::parser::exception::ParserException::make_message(int line, const std::string &origin, const std::string &message) {
    std::stringstream s;

    if (line > 0) {  // Error was found in a specific line
        s << "ParserError at line: " << line;
    }else{   // the error was generated by encountering the end of file when unexpected.
        s << "ParserError at EOF: ";
    }

    s << message << std::endl;
    s << "\tfrom origin: " << origin;
    return s.str();
}

int extract_line_number_from_token(Token *token) {
    if (token) {
        return token->get_line_number();
    }else{
        return -1;
    }
}

ninx::parser::exception::ParserException::ParserException(Token *token, std::string &origin,
                                                          const std::string &message) :
                                                          ParserException(extract_line_number_from_token(token),
                                                                  origin, message){}